version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Szemethegy1970
      POSTGRES_DB: finvault
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
